### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by michaelchow2324** [Slins-23/flutter-fft#7]
This is a very good plugin, hope to see IOS support soon!

**Comment by Slins-23** [comment]
Thanks, glad you find it useful! Unfortunately it's probably not happening anytime soon, given I don't have an iPhone or Mac.

**Comment by TomPeak** [comment]
I need your pub badly for AudioVisualizion and on iOS, I send you an iPhone! :) Is ist possible to have it on internal Audio?I use just_audio for playing the stream.  Please keep this project alife! THX, Tom

**Comment by Slins-23** [comment]
Hey! Glad you found it useful!

If by internal audio you mean sound emitted from the phone, then yes. As long as there's a way to get the audio data, any audio can be processed. 

For this plugin specifically there would need to be some changes in order to allow this (you can do it yourself if you know your way around, it's not complex), as it defaults to using the microphone.

I never really maintained this code, as it was the byproduct of my learning projects and I have moved on to new ones since. I found out by accident that people were using it, so I dedicated some time a few months ago into updating it and fixing some issues people had.

I shouldn't focus on it because I'm studying other topics. But since some people are asking for it, I can spend a week or so making the iOS version, but I can't focus for long on this project.

If you really want to send me one, you can email me at slins312@gmail.com.

**Comment by SarthakZunroof** [comment]
I am working on a project, Which is related to animate frequency as per the external sound. What I mean is I want to input external sound(music) through microphone and using the frequency of the live music I want to animate my visualizer. Any idea how to do that ?

**Comment by Slins-23** [comment]
> I am working on a project, Which is related to animate frequency as per the external sound. What I mean is I want to input external sound(music) through microphone and using the frequency of the live music I want to animate my visualizer. Any idea how to do that ?

I haven't tested it outside of standalone notes, so I can't really give you a formula here or tell you how accurate it is. However, you could try decreasing the detection interval in the settings, so that it can detect more notes in a shorter time span and give you what you're aiming for.
